version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pmem_mysql
    restart: always
    environment:
      MYSQL_DATABASE: pmem_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - pmem-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pmem_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - pmem-network

volumes:
  mysql_data:

networks:
  pmem-network:
    driver: bridge
